// WORDS

export const GET_WORD_SUCCESS = "GET_WORD_SUCCESS"
export const GET_WORD_FAILED = "GET_WORD_fAILED"

export const GET_WORDS_SUCCESS = "GET_WORDS_SUCCESS"
export const GET_WORDS_FAILED = "GET_WORDS_FAILED"

export const POST_WORD_SUCCESS = "POST_WORD_SUCCESS"
export const POST_WORD_FAILED = "POST_WORD_FAILED"

export const DELETE_WORD_SUCCESS = "DELETE_WORD_SUCCESS"
export const DELETE_WORD_FAILED = "DELETE_WORD_FAILED"